### ISSUE TITLE
Extension can't be uploaded/installed

### ISSUE THREAD

**Issue by UFHH01** [plesk/ext-google-url-shortener#1]
Hi, the following error appears, when trying to install the extension over:

=> HOME > Extensions > Upload Extensions

with the current *.zip - file: => https://github.com/plesk/ext-google-url-shortener/archive/master.zip

Error message:
`Error: Unable to install the extension:
Corrupted meta.xml file.`

System: Ubuntu 16.04, Plesk Onyx 17.0.17 ( #MU 18 )

**Comment by Kubik-Rubik** [comment]
Hi @UFHH01,

thank you for testing!

The `meta.xml` (and the other files) must be in the root of the zip archive. GitHub creates the archive with a (sub)folder and puts the code into this folder. Please download the archive you've linked, unzip it on your local machine and create a new zip archive (not the single folder in the root but one level down with all files).

Would it help if I would provide a ready-to-go installation package?

Cheers

**Comment by UFHH01** [comment]
aaaAAAaaahhhh ^^.... sorry for my little knowledge. You are absolutely correct.

I don't think, that "normal" github - user don't know the "folder-inside-folder" - issue, when testing - but if you would like more unexperienced user to test the extension, it could help to avoid error - reports like mine, if you extend it with an installation  - documentation, I think. :-)
